### ISSUE TITLE
Create a .gitignore for the project

### ISSUE THREAD

**Issue by hkakutalua** [gdgluanda/rapidinho#11]
We really need to keep out our IDEs leftovers out of the project.

**Comment by hkakutalua** [comment]
Related modifications:
https://github.com/gdgluanda/rapidinho/commit/2f5fc6b791a58a13e06058b5e5f56a960382f898

**Comment by braulio94** [comment]
Now I can't load the project on my Computer

**Comment by hkakutalua** [comment]
What kind of error appears?
I'll try to clone and open again.

**Comment by hkakutalua** [comment]
Hey @braulio94, i made the clone again with git, i opened the project, downloaded all the dependencies and it's working without issues.

Except for this:
![Screenshot](https://user-images.githubusercontent.com/3662164/45355520-8254b700-b5b8-11e8-94ca-af48f5c90c51.png)

**Comment by hkakutalua** [comment]
Any update @braulio94?

**Comment by braulio94** [comment]
Weirdly doesn't seem to be happening again. I can't replicate the error to find out what may be causing it.

**Comment by braulio94** [comment]
Just found out what's causing this error. 
It happens when the Textfield in the HomeTab is focused and the user moves to another tab and back.

We might have to remove the search Textfield from the HomeTab temporarily and implement it properly later.
