### ISSUE TITLE
BottomNavigation

### ISSUE THREAD

**Issue by braulio94** [gdgluanda/rapidinho#3]
Every modern app nowadays has some sort of BottomNavigation widget.
Since @pedromassango  is the expert in this topic for writing [an article](https://medium.com/flutterpub/my-flutter-path-001-bottom-navigation-bar-71cc47df4d9f) on it I'm going to leave this to him. 

The items the BottomNavigation is going to have is up to you for now. Later we will see if makes sense.

**Comment by pedromassango** [comment]
I think that I did it

**Comment by braulio94** [comment]
Thank you Pedro. 

Issues shouldn't be closed until everyone agrees. I think the colors don't go with the app's theme. 
Let's see what @Henry-Keys  has to say. 


![image](https://raw.githubusercontent.com/gdgluanda/rapidinho/master/screenshots/home2.png)

**Comment by hkakutalua** [comment]
Hey @pedromassango, good job on that.
Just one question.
What the hamburguer icon 🍔 represents in the bottom navigation?

**Comment by braulio94** [comment]
Didn't notice that. 
By the way, @pedromassango I'm having trouble merging your changes.

**Comment by pedromassango** [comment]
@Henry-Keys this icon mean a list of orders. Also it is temporary

**Comment by pedromassango** [comment]
@braulio94  when I made the pull, I was unable to build the project, so I need to update the flutter SDK

**Comment by pedromassango** [comment]
Also, for each selected item in  bottom navigation it will change the bottom navigation background.

**Comment by braulio94** [comment]
I had to clone the repo again is now working fine.
For now let's leave it as is, will make changes later on. Great job @pedromassango ☺️

**Comment by braulio94** [comment]
I have update the BottomNavigationBar hope you don't mind @pedromassango
