### ISSUE TITLE
Exit AlertDialog

### ISSUE THREAD

**Issue by braulio94** [gdgluanda/rapidinho#7]
Show a beautifully customized AlertDialog when the user presses the back button when in HomePage.
This AlertDialog should have a positive and negative button and show the following message: 
"Are you sure you want to exit the app?"

Implementation is done [here](https://github.com/gdgluanda/rapidinho/blob/master/lib/home_page.dart#L60)

**Comment by pedromassango** [comment]
Should the message be in English?

**Comment by pedromassango** [comment]
I did it.

**Comment by braulio94** [comment]
It should be in Portuguese.

**Comment by braulio94** [comment]
**LGTM**

**Comment by pedromassango** [comment]
Yah, it is in Portuguese

**Comment by pedromassango** [comment]
Can be closed?

**Comment by braulio94** [comment]
Hey @pedromassango, can you please make the application close/exit when the user clicks on the positive button(in the dialog) ? And not actually go back to the splash screen?

**Comment by pedromassango** [comment]
I already did it

**Comment by pedromassango** [comment]
On this commit:
https://github.com/gdgluanda/rapidinho/commit/2002dc61e7f86630a74188150a5b249ae6f4f665

**Comment by braulio94** [comment]
Left a comment yesterday on this commit. Check it out.
